/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    posts: Post;
    providers: Provider;
    media: Media;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    providers: ProvidersSelect<false> | ProvidersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  roles: ('super-admin' | 'content-editor' | 'support-admin' | 'family-member')[];
  mustResetPassword?: boolean | null;
  onboardingStatus?: ('NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED') | null;
  onboardingStep?: number | null;
  onboardingData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Internal page title used in the admin list.
   */
  title: string;
  /**
   * Use "home" for the homepage.
   */
  slug: string;
  /**
   * The primary page hero is a reusable Payload block. Add exactly one hero block.
   */
  hero?: HeroBlock[] | null;
  /**
   * Reusable content sections that render below the hero.
   */
  layout: (
    | FeatureGridBlock
    | StatsBlock
    | ContentBlock
    | CTABlock
    | MediaBlock
    | TestimonialBlock
    | FAQBlock
    | LegalArticleBlock
    | ContactFormBlock
    | PartnershipCardsBlock
    | BlogArchiveBlock
  )[];
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Optional HTML id for anchor links.
   */
  sectionId?: string | null;
  variant: 'marketing' | 'app';
  theme?: ('light' | 'brand') | null;
  eyebrow?: string | null;
  title: string;
  highlight?: string | null;
  body?: string | null;
  actions?:
    | {
        label: string;
        href: string;
        variant?: ('primary' | 'secondary' | 'accent') | null;
        iconKey?:
          | (
              | 'arrowRight'
              | 'award'
              | 'barChart'
              | 'bell'
              | 'bookOpen'
              | 'building'
              | 'calendar'
              | 'calendarDays'
              | 'checkCircle'
              | 'clock'
              | 'database'
              | 'eye'
              | 'fileText'
              | 'globe'
              | 'heart'
              | 'lock'
              | 'mail'
              | 'mapPin'
              | 'messageSquare'
              | 'phone'
              | 'scale'
              | 'send'
              | 'shield'
              | 'sparkles'
              | 'target'
              | 'trendingUp'
              | 'users'
              | 'video'
              | 'wallet'
              | 'zap'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  media?: {
    kind?: ('none' | 'carousel' | 'image') | null;
    /**
     * Choose an image from Payload Media.
     */
    image?: (number | null) | Media;
    /**
     * Choose carousel images from Payload Media.
     */
    images?:
      | {
          image: number | Media;
          /**
           * Optional override. Defaults to the Media alt text.
           */
          alt?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional override. Defaults to the Media alt text.
     */
    alt?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  /**
   * Optional HTML id for anchor links.
   */
  sectionId?: string | null;
  title: string;
  intro?: string | null;
  layout?: ('cards' | 'compact') | null;
  /**
   * Controls desktop card columns. Overflow rows are centered automatically.
   */
  cardsPerRow?: ('2' | '3' | '4') | null;
  background?: ('plain' | 'muted') | null;
  items: {
    title: string;
    body: string;
    /**
     * Optional card image from Payload Media. When set, it replaces the icon treatment.
     */
    image?: (number | null) | Media;
    /**
     * Optional override. Defaults to the Media alt text.
     */
    imageAlt?: string | null;
    iconKey?:
      | (
          | 'arrowRight'
          | 'award'
          | 'barChart'
          | 'bell'
          | 'bookOpen'
          | 'building'
          | 'calendar'
          | 'calendarDays'
          | 'checkCircle'
          | 'clock'
          | 'database'
          | 'eye'
          | 'fileText'
          | 'globe'
          | 'heart'
          | 'lock'
          | 'mail'
          | 'mapPin'
          | 'messageSquare'
          | 'phone'
          | 'scale'
          | 'send'
          | 'shield'
          | 'sparkles'
          | 'target'
          | 'trendingUp'
          | 'users'
          | 'video'
          | 'wallet'
          | 'zap'
        )
      | null;
    accentPreset?:
      | ('brandBlue' | 'careGreen' | 'warmGold' | 'familyPurple' | 'alertRose' | 'supportOrange' | 'brandGradient')
      | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  /**
   * Optional HTML id for anchor links.
   */
  sectionId?: string | null;
  title?: string | null;
  intro?: string | null;
  variant?: ('metrics' | 'steps') | null;
  background?: ('plain' | 'muted') | null;
  items: {
    value: string;
    label: string;
    description?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  /**
   * Optional HTML id for anchor links.
   */
  sectionId?: string | null;
  title?: string | null;
  intro?: string | null;
  prose?: string | null;
  bullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  actions?:
    | {
        label: string;
        href: string;
        variant?: ('primary' | 'secondary' | 'accent') | null;
        iconKey?:
          | (
              | 'arrowRight'
              | 'award'
              | 'barChart'
              | 'bell'
              | 'bookOpen'
              | 'building'
              | 'calendar'
              | 'calendarDays'
              | 'checkCircle'
              | 'clock'
              | 'database'
              | 'eye'
              | 'fileText'
              | 'globe'
              | 'heart'
              | 'lock'
              | 'mail'
              | 'mapPin'
              | 'messageSquare'
              | 'phone'
              | 'scale'
              | 'send'
              | 'shield'
              | 'sparkles'
              | 'target'
              | 'trendingUp'
              | 'users'
              | 'video'
              | 'wallet'
              | 'zap'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  aside?: {
    title?: string | null;
    body?: string | null;
    /**
     * Optional image from Payload Media. When set, the aside renders as an image panel.
     */
    image?: (number | null) | Media;
    /**
     * Optional override. Defaults to the Media alt text.
     */
    imageAlt?: string | null;
    actions?:
      | {
          label: string;
          href: string;
          variant?: ('primary' | 'secondary' | 'accent') | null;
          iconKey?:
            | (
                | 'arrowRight'
                | 'award'
                | 'barChart'
                | 'bell'
                | 'bookOpen'
                | 'building'
                | 'calendar'
                | 'calendarDays'
                | 'checkCircle'
                | 'clock'
                | 'database'
                | 'eye'
                | 'fileText'
                | 'globe'
                | 'heart'
                | 'lock'
                | 'mail'
                | 'mapPin'
                | 'messageSquare'
                | 'phone'
                | 'scale'
                | 'send'
                | 'shield'
                | 'sparkles'
                | 'target'
                | 'trendingUp'
                | 'users'
                | 'video'
                | 'wallet'
                | 'zap'
              )
            | null;
          id?: string | null;
        }[]
      | null;
    note?: string | null;
  };
  layout?: ('centered' | 'split') | null;
  background?: ('plain' | 'muted') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  /**
   * Optional HTML id for anchor links.
   */
  sectionId?: string | null;
  title: string;
  body?: string | null;
  actions?:
    | {
        label: string;
        href: string;
        variant?: ('primary' | 'secondary' | 'accent') | null;
        iconKey?:
          | (
              | 'arrowRight'
              | 'award'
              | 'barChart'
              | 'bell'
              | 'bookOpen'
              | 'building'
              | 'calendar'
              | 'calendarDays'
              | 'checkCircle'
              | 'clock'
              | 'database'
              | 'eye'
              | 'fileText'
              | 'globe'
              | 'heart'
              | 'lock'
              | 'mail'
              | 'mapPin'
              | 'messageSquare'
              | 'phone'
              | 'scale'
              | 'send'
              | 'shield'
              | 'sparkles'
              | 'target'
              | 'trendingUp'
              | 'users'
              | 'video'
              | 'wallet'
              | 'zap'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  note?: string | null;
  theme?: ('brand' | 'slate') | null;
  /**
   * Optional decorative background pattern for the CTA band.
   */
  pattern?: ('none' | 'softGrid' | 'careDots' | 'diagonalLines' | 'gentleWaves') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  /**
   * Optional HTML id for anchor links.
   */
  sectionId?: string | null;
  image: number | Media;
  /**
   * Optional override. Defaults to the Media alt text.
   */
  alt?: string | null;
  caption?: string | null;
  layout?: ('contained' | 'wide') | null;
  background?: ('plain' | 'muted') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'media';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock".
 */
export interface TestimonialBlock {
  /**
   * Optional HTML id for anchor links.
   */
  sectionId?: string | null;
  quote: string;
  author: string;
  role?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  /**
   * Optional HTML id for anchor links.
   */
  sectionId?: string | null;
  title: string;
  intro?: string | null;
  items: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LegalArticleBlock".
 */
export interface LegalArticleBlock {
  /**
   * Optional HTML id for anchor links.
   */
  sectionId?: string | null;
  title: string;
  lastUpdated?: string | null;
  intro?: string | null;
  sections: {
    anchor: string;
    title: string;
    iconKey?:
      | (
          | 'arrowRight'
          | 'award'
          | 'barChart'
          | 'bell'
          | 'bookOpen'
          | 'building'
          | 'calendar'
          | 'calendarDays'
          | 'checkCircle'
          | 'clock'
          | 'database'
          | 'eye'
          | 'fileText'
          | 'globe'
          | 'heart'
          | 'lock'
          | 'mail'
          | 'mapPin'
          | 'messageSquare'
          | 'phone'
          | 'scale'
          | 'send'
          | 'shield'
          | 'sparkles'
          | 'target'
          | 'trendingUp'
          | 'users'
          | 'video'
          | 'wallet'
          | 'zap'
        )
      | null;
    body?: string | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'legalArticle';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  /**
   * Optional HTML id for anchor links.
   */
  sectionId?: string | null;
  title: string;
  intro?: string | null;
  inquiryTypes?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  contactCards?:
    | {
        title: string;
        body: string;
        href?: string | null;
        iconKey?:
          | (
              | 'arrowRight'
              | 'award'
              | 'barChart'
              | 'bell'
              | 'bookOpen'
              | 'building'
              | 'calendar'
              | 'calendarDays'
              | 'checkCircle'
              | 'clock'
              | 'database'
              | 'eye'
              | 'fileText'
              | 'globe'
              | 'heart'
              | 'lock'
              | 'mail'
              | 'mapPin'
              | 'messageSquare'
              | 'phone'
              | 'scale'
              | 'send'
              | 'shield'
              | 'sparkles'
              | 'target'
              | 'trendingUp'
              | 'users'
              | 'video'
              | 'wallet'
              | 'zap'
            )
          | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnershipCardsBlock".
 */
export interface PartnershipCardsBlock {
  /**
   * Optional HTML id for anchor links.
   */
  sectionId?: string | null;
  title: string;
  intro?: string | null;
  items: {
    title: string;
    subtitle?: string | null;
    body: string;
    iconKey?:
      | (
          | 'arrowRight'
          | 'award'
          | 'barChart'
          | 'bell'
          | 'bookOpen'
          | 'building'
          | 'calendar'
          | 'calendarDays'
          | 'checkCircle'
          | 'clock'
          | 'database'
          | 'eye'
          | 'fileText'
          | 'globe'
          | 'heart'
          | 'lock'
          | 'mail'
          | 'mapPin'
          | 'messageSquare'
          | 'phone'
          | 'scale'
          | 'send'
          | 'shield'
          | 'sparkles'
          | 'target'
          | 'trendingUp'
          | 'users'
          | 'video'
          | 'wallet'
          | 'zap'
        )
      | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    actions?:
      | {
          label: string;
          href: string;
          variant?: ('primary' | 'secondary' | 'accent') | null;
          iconKey?:
            | (
                | 'arrowRight'
                | 'award'
                | 'barChart'
                | 'bell'
                | 'bookOpen'
                | 'building'
                | 'calendar'
                | 'calendarDays'
                | 'checkCircle'
                | 'clock'
                | 'database'
                | 'eye'
                | 'fileText'
                | 'globe'
                | 'heart'
                | 'lock'
                | 'mail'
                | 'mapPin'
                | 'messageSquare'
                | 'phone'
                | 'scale'
                | 'send'
                | 'shield'
                | 'sparkles'
                | 'target'
                | 'trendingUp'
                | 'users'
                | 'video'
                | 'wallet'
                | 'zap'
              )
            | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'partnershipCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogArchiveBlock".
 */
export interface BlogArchiveBlock {
  /**
   * Optional HTML id for anchor links.
   */
  sectionId?: string | null;
  title: string;
  intro?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogArchive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  category:
    | 'CAREGIVING_TIPS'
    | 'FAMILY_STORIES'
    | 'HEALTH_WELLNESS'
    | 'FINANCIAL_PLANNING'
    | 'TECHNOLOGY'
    | 'LEGAL_MATTERS'
    | 'COMPANY_NEWS';
  author: string;
  authorTitle?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Legacy fallback only. Prefer Cover Image from Payload Media.
   */
  coverImageUrl?: string | null;
  content: string;
  readTime?: number | null;
  publishedAt?: string | null;
  relatedPosts?: (number | Post)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers".
 */
export interface Provider {
  id: number;
  name: string;
  category:
    | 'HOME_HEALTH_AIDE'
    | 'MEAL_DELIVERY'
    | 'TRANSPORTATION'
    | 'ADULT_DAY_CARE'
    | 'RESPITE_CARE'
    | 'LEGAL_FINANCIAL'
    | 'MEDICAL_EQUIPMENT';
  description: string;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  serviceArea?: string | null;
  logo?: (number | null) | Media;
  vetted?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  type: 'general' | 'support' | 'partnership' | 'press' | 'feedback';
  subject: string;
  message: string;
  status: 'new' | 'in-progress' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  roles?: T;
  mustResetPassword?: T;
  onboardingStatus?: T;
  onboardingStep?: T;
  onboardingData?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
      };
  layout?:
    | T
    | {
        featureGrid?: T | FeatureGridBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        media?: T | MediaBlockSelect<T>;
        testimonial?: T | TestimonialBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        legalArticle?: T | LegalArticleBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        partnershipCards?: T | PartnershipCardsBlockSelect<T>;
        blogArchive?: T | BlogArchiveBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  sectionId?: T;
  variant?: T;
  theme?: T;
  eyebrow?: T;
  title?: T;
  highlight?: T;
  body?: T;
  actions?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        iconKey?: T;
        id?: T;
      };
  media?:
    | T
    | {
        kind?: T;
        image?: T;
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        alt?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  sectionId?: T;
  title?: T;
  intro?: T;
  layout?: T;
  cardsPerRow?: T;
  background?: T;
  items?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        imageAlt?: T;
        iconKey?: T;
        accentPreset?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  sectionId?: T;
  title?: T;
  intro?: T;
  variant?: T;
  background?: T;
  items?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  sectionId?: T;
  title?: T;
  intro?: T;
  prose?: T;
  bullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  actions?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        iconKey?: T;
        id?: T;
      };
  aside?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        imageAlt?: T;
        actions?:
          | T
          | {
              label?: T;
              href?: T;
              variant?: T;
              iconKey?: T;
              id?: T;
            };
        note?: T;
      };
  layout?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  sectionId?: T;
  title?: T;
  body?: T;
  actions?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        iconKey?: T;
        id?: T;
      };
  note?: T;
  theme?: T;
  pattern?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  sectionId?: T;
  image?: T;
  alt?: T;
  caption?: T;
  layout?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock_select".
 */
export interface TestimonialBlockSelect<T extends boolean = true> {
  sectionId?: T;
  quote?: T;
  author?: T;
  role?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  sectionId?: T;
  title?: T;
  intro?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LegalArticleBlock_select".
 */
export interface LegalArticleBlockSelect<T extends boolean = true> {
  sectionId?: T;
  title?: T;
  lastUpdated?: T;
  intro?: T;
  sections?:
    | T
    | {
        anchor?: T;
        title?: T;
        iconKey?: T;
        body?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock_select".
 */
export interface ContactFormBlockSelect<T extends boolean = true> {
  sectionId?: T;
  title?: T;
  intro?: T;
  inquiryTypes?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  contactCards?:
    | T
    | {
        title?: T;
        body?: T;
        href?: T;
        iconKey?: T;
        note?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnershipCardsBlock_select".
 */
export interface PartnershipCardsBlockSelect<T extends boolean = true> {
  sectionId?: T;
  title?: T;
  intro?: T;
  items?:
    | T
    | {
        title?: T;
        subtitle?: T;
        body?: T;
        iconKey?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        actions?:
          | T
          | {
              label?: T;
              href?: T;
              variant?: T;
              iconKey?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogArchiveBlock_select".
 */
export interface BlogArchiveBlockSelect<T extends boolean = true> {
  sectionId?: T;
  title?: T;
  intro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  author?: T;
  authorTitle?: T;
  coverImage?: T;
  coverImageUrl?: T;
  content?: T;
  readTime?: T;
  publishedAt?: T;
  relatedPosts?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers_select".
 */
export interface ProvidersSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  description?: T;
  phone?: T;
  email?: T;
  website?: T;
  serviceArea?: T;
  logo?: T;
  vetted?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  type?: T;
  subject?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}